CC      = x86_64-w64-mingw32-gcc
CFLAGS  = -std=c99 -Wall -O3 -g3

key-collab.exe : key-collab.c platform_mingw.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

wordlist :
	curl -o $@ 'http://pastebin.com/raw.php?i=9aFn1r27'

.PHONY : test clean distclean

test : key-collab.exe wordlist
	./$^ < wordlist

clean :
	$(RM) key-collab.exe

distclean : clean
	$(RM) wordlist
